SELECT 
dbo.TBABYCARD.FID,
dbo.TBABYCARD.FPRN,
dbo.TBABYCARD.FTIMES,
dbo.TBABYCARD.FBABYNUM,
dbo.TBABYCARD.FBABYSEXBH,
dbo.TBABYCARD.FBABYSEX,
CONVERT(NUMERIC(18,2), dbo.TBABYCARD.FTZ) / 1000,
dbo.TBABYCARD.FRESULTBH,
dbo.TBABYCARD.FRESULT,
dbo.TBABYCARD.FZGBH,
dbo.TBABYCARD.FZG,
dbo.TBABYCARD.FBABYSUC,
dbo.TBABYCARD.FHXBH,
dbo.TBABYCARD.FHX 

FROM 
dbo.TBABYCARD 
WHERE 
dbo.TBABYCARD.FID 