DECLARE @zy VARCHAR(20) 
DECLARE @qh VARCHAR(6) 
DECLARE @tp VARCHAR(20) 
DECLARE @sfz VARCHAR(30) 

SELECT 
@zy = db_upload.dbo.TABLEUPLOAD.InSurVisitId, 
@qh = db_upload.dbo.TABLEUPLOAD.CBDTCQH, 
@tp = db_upload.dbo.TABLEUPLOAD.FIDCARD_TYPE, 
@sfz = db_upload.dbo.TABLEUPLOAD.FIDCARD 
FROM dbo.TABLEUPLOAD 
WHERE dbo.TABLEUPLOAD.FPRN = @bah AND dbo.TABLEUPLOAD.FTIMES = @cs 

INSERT INTO db_upload.dbo.TABLES(
dbo.TABLES.SID,
dbo.TABLES.FPRN,
dbo.TABLES.FTIMES,
dbo.TABLES.InSurVisitId,
dbo.TABLES.CBDTCQH,
dbo.TABLES.FIDCARD_TYPE,
dbo.TABLES.FIDCARD,
dbo.TABLES.SPX,
dbo.TABLES.SSSM,
dbo.TABLES.SSSNAME,
dbo.TABLES.SSDATE,
dbo.TABLES.SQKBH,
dbo.TABLES.SQK,
dbo.TABLES.SYHBH,
dbo.TABLES.SYH,
dbo.TABLES.SSSYSBH,
dbo.TABLES.SSSYS,
dbo.TABLES.SMZFSBH,
dbo.TABLES.SMZFS,
dbo.TABLES.SSFFJSS,
dbo.TABLES.SIZBH,
dbo.TABLES.SIZNAME,
dbo.TABLES.SIIZBH,
dbo.TABLES.SIIZNAME,
dbo.TABLES.SMZYSBH,
dbo.TABLES.SMZYS,
dbo.TABLES.SZQSSBH,
dbo.TABLES.SZQSS,
dbo.TABLES.SSSJBBH,
dbo.TABLES.SSSJB)

VALUES (