DECLARE @id VARCHAR(20) 
DECLARE @zy VARCHAR(20) 
DECLARE @qh VARCHAR(20) 
DECLARE @cbd VARCHAR(20) 
DECLARE @cbx VARCHAR(20) 
DECLARE @cby VARCHAR(20) 

SELECT @id = nhis.dbo.InVisit.InVisitId 
FROM nhis.dbo.InVisit 
WHERE nhis.dbo.InVisit.Name = @name AND nhis.dbo.InVisit.DischargeDT = @cyt 

SELECT @zy = nhis.dbo.ZhaoQingInVisitSiReg.InSurVisitId, @qh = nhis.dbo.ZhaoQingInVisitSiReg.JBJGCode, @cbd = nhis.dbo.ZhaoQingInVisitSiReg.JBJGName, @cbx = nhis.dbo.ZhaoQingInVisitSiReg.PersonType, @cby = nhis.dbo.ZhaoQingInVisitSiReg.isyd 
FROM nhis.dbo.ZhaoQingInVisitSiReg 
WHERE nhis.dbo.ZhaoQingInVisitSiReg.VisitId = @id 

INSERT INTO [db_upload].[dbo].[TABLEUPLOAD] (FID_TPATIENTVISIT,FID_ZhaoQingInVisitSiRegId,InSurVisitId,CBDTCQH,FIDCARD_TYPE,FIDCARD,FPRN,FTIMES,FICDVERSION,FZYID,FAGE,FNAME,FSEXBH,FBIRTHDAY,FBIRTHPLACE,FCOUNTRYBH,FCOUNTRY,FNATIONALITYBH,FNATIONALITY,FJOB,FSTATUSBH,FSTATUS,FDWNAME,FDWADDR,FDWTELE,FDWPOST,FHKADDR,FHKPOST,FLXNAME,FRELATE,FLXADDR,FLXTELE,FJKKH,FRYDATE,FRYTYKH,FRYDEPT,FRYBS,FCYDATE,FCYTYKH,FCYDEPT,FCYBS,FDAYS,FMZZDBH,FMZZD,FMZDOCTBH,FMZDOCT,FPHZD,FGMYW,FQJTIMES,FQJSUCTIMES,FKZRBH,FKZR,FZRDOCTBH,FZRDOCTOR,FZZDOCTBH,FZZDOCT,FZYDOCTBH,FZYDOCT,FJXDOCTBH,FJXDOCT,FSXDOCTBH,FSXDOCT,FBMYBH,FBMY,FQUALITYBH,FQUALITY,FZKDOCTBH,FZKDOCT,FZKNURSEBH,FZKNURSE,FZKRQ,FSUM1,FXYF,FZYF,FZCHYF,FZCYF,FQTF,FBODYBH,FBODY,FBLOODBH,FBLOOD,FRHBH,FRH,FZKTYKH,FZKDEPT,FZKDATE,FZKTIME,FJBFXBH,FJBFX,FNATIVE,FCURRADDR,FCURRTELE,FCURRPOST,FJOBBH,FCSTZ,FRYTZ,FRYTJBH,FRYTJ,FYCLJBH,FYCLJ,FPHZDBH,FPHZDNUM,FIFGMYWBH,FIFGMYW,FNURSEBH,FNURSE,FLYFSBH,FLYFS,FYZOUTHOSTITAL,FSQOUTHOSTITAL,FISAGAINRYBH,FISAGAINRY,FISAGAINRYMD,FRYQHMDAYS,FRYQHMHOURS,FRYQHMMINS,FRYQHMCOUNTS,FRYHMDAYS,FRYHMHOURS,FRYHMMINS,FRYHMCOUNTS,FFBBHNEW,FFBNEW,FZFJE,FZHFWLYLF,FZHFWLCZF,FZHFWLHLF,FZHFWLQTF,FZDLBLF,FZDLSSSF,FZDLYXF,FZDLLCF,FZLLFFSSF,FZLLFWLZWLF,FZLLFSSF,FZLLFMZF,FZLLFSSZLF,FKFLKFF,FZYLZF,FXYLGJF,FXYLXF,FXYLBQBF,FXYLQDBF,FXYLYXYZF,FXYLXBYZF,FHCLCJF,FHCLZLF,FHCLSSF,FZHFWLYLF01,FZHFWLYLF02,JBJGName,PersonType,isyd) 
VALUES (