INSERT INTO db_upload.dbo.TABLEZ(
dbo.TABLEZ.ZID,
dbo.TABLEZ.FPRN,
dbo.TABLEZ.FTIMES,
dbo.TABLEZ.ZPX,
dbo.TABLEZ.ZZDLX,
dbo.TABLEZ.ZJBMC,
dbo.TABLEZ.ZICDM,
dbo.TABLEZ.ZRYBQBH,
dbo.TABLEZ.ZRYBQ)

VALUES (