DECLARE @zy VARCHAR(20) 
DECLARE @qh VARCHAR(6) 
DECLARE @tp VARCHAR(20) 
DECLARE @sfz VARCHAR(30) 

SELECT 
@zy = db_upload.dbo.TABLEUPLOAD.InSurVisitId, 
@qh = db_upload.dbo.TABLEUPLOAD.CBDTCQH, 
@tp = db_upload.dbo.TABLEUPLOAD.FIDCARD_TYPE, 
@sfz = db_upload.dbo.TABLEUPLOAD.FIDCARD 
FROM dbo.TABLEUPLOAD 
WHERE dbo.TABLEUPLOAD.FPRN = @bah AND dbo.TABLEUPLOAD.FTIMES = @cs 

INSERT INTO db_upload.dbo.TABLEBABY(
dbo.TABLEBABY.BID,
dbo.TABLEBABY.FPRN,
dbo.TABLEBABY.FTIMES,
dbo.TABLEBABY.InSurVisitId,
dbo.TABLEBABY.CBDTCQH,
dbo.TABLEBABY.FIDCARD_TYPE,
dbo.TABLEBABY.FIDCARD,
dbo.TABLEBABY.BPX,
dbo.TABLEBABY.BXBBH,
dbo.TABLEBABY.BXB,
dbo.TABLEBABY.BTZ,
dbo.TABLEBABY.BFMJGBH,
dbo.TABLEBABY.BFMJG,
dbo.TABLEBABY.BZGBH,
dbo.TABLEBABY.BZG,
dbo.TABLEBABY.BYEQJCGCS,
dbo.TABLEBABY.BHXBH,
dbo.TABLEBABY.BHX) 

VALUES (