SELECT 
dbo.TOPERATION.FID,
dbo.TOPERATION.FPRN,
dbo.TOPERATION.FTIMES,
dbo.TOPERATION.FOPTIMES,
dbo.TOPERATION.FOPCODE,
dbo.TOPERATION.FOP,
dbo.TOPERATION.FOPDATE,
dbo.TOPERATION.FQIEKOUBH,
dbo.TOPERATION.FQIEKOU,
dbo.TOPERATION.FYUHEBH,
dbo.TOPERATION.FYUHE,
CASE 
	WHEN dbo.TOPERATION.FDOCBH = '' OR dbo.TOPERATION.FDOCBH IS NULL THEN '-' 
	ELSE dbo.TOPERATION.FDOCBH 
END, 
dbo.TOPERATION.FDOCNAME,
dbo.TOPERATION.FMAZUIBH,
dbo.TOPERATION.FMAZUI,
dbo.TOPERATION.FIFFSOP,
CASE 
	WHEN dbo.TOPERATION.FOPDOCT1BH = '' OR dbo.TOPERATION.FOPDOCT1BH IS NULL THEN '-' 
	ELSE dbo.TOPERATION.FOPDOCT1BH 
END, 
CASE 
	WHEN dbo.TOPERATION.FOPDOCT1 = '' OR dbo.TOPERATION.FOPDOCT1 IS NULL THEN '-' 
	ELSE dbo.TOPERATION.FOPDOCT1 
END, 
CASE 
	WHEN dbo.TOPERATION.FOPDOCT2BH = '' OR dbo.TOPERATION.FOPDOCT2BH IS NULL THEN '-' 
	ELSE dbo.TOPERATION.FOPDOCT2BH 
END, 
CASE 
	WHEN dbo.TOPERATION.FOPDOCT2 = '' OR dbo.TOPERATION.FOPDOCT2 IS NULL THEN '-' 
	ELSE dbo.TOPERATION.FOPDOCT2 
END, 
dbo.TOPERATION.FMZDOCTBH,
dbo.TOPERATION.FMZDOCT,
dbo.TOPERATION.FZQSSBH,
dbo.TOPERATION.FZQSS,
dbo.TOPERATION.FSSJBBH,
dbo.TOPERATION.FSSJB 

FROM 
dbo.TOPERATION 
WHERE 
dbo.TOPERATION.FID 