SELECT 
TDIAGNOSE.FID,
TDIAGNOSE.FPRN,
TDIAGNOSE.FTIMES,
TDIAGNOSE.FZDLX,
TDIAGNOSE.FICDVERSION,
TDIAGNOSE.FICDM,
TDIAGNOSE.FJBNAME,
TDIAGNOSE.FZLJGBH,
TDIAGNOSE.FZLJG,
TDIAGNOSE.FPX,
TDIAGNOSE.FRYBQBH,
TDIAGNOSE.FRYBQ 

FROM 
bagl_java.dbo.TDIAGNOSE 
WHERE 
TDIAGNOSE.FID